--------------------------------------------------------
--  Fichier créé - jeudi-novembre-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEEC
--------------------------------------------------------

  CREATE TABLE "HOUSSEM"."EMPLOYEEC" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NP" VARCHAR2(20 BYTE), 
	"STAT" VARCHAR2(20 BYTE), 
	"SAL" VARCHAR2(20 BYTE), 
	"POST" VARCHAR2(20 BYTE), 
	"DIP" VARCHAR2(20 BYTE), 
	"PT" VARCHAR2(20 BYTE), 
	"NBC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOUSSEM.EMPLOYEEC
SET DEFINE OFF;
Insert into HOUSSEM.EMPLOYEEC (ID,NP,STAT,SAL,POST,DIP,PT,NBC) values ('aa','a','a','a','sas','sa','s','sss');
--------------------------------------------------------
--  DDL for Index EMPLOYEEC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOUSSEM"."EMPLOYEEC_PK" ON "HOUSSEM"."EMPLOYEEC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEEC
--------------------------------------------------------

  ALTER TABLE "HOUSSEM"."EMPLOYEEC" ADD CONSTRAINT "EMPLOYEEC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOUSSEM"."EMPLOYEEC" MODIFY ("ID" NOT NULL ENABLE);
